word_limit = {
    "title": 20, 
    "proposedBy": 10,
    "introduction": 200,
    "briefSummary": 200,
    "objectives": 150,
    "address": 50,
    "phoneNumber": 20,
    "email": 30,
    "website": 30,
    "referenceNumber": 20,  
    "submissionDate": 15,  
    "backgroundAndExperience": 250,
    "whyChooseUs": 150,
    "clientRequirements": 200,
    "uniqueSellingProposition": 100,
    "scopeOfWork": 250,
    "projectTeam": 150,
    "projectSchedule": 100,
    "estimatedProjectCost": 100,
    "breakdownOfCosts": 200,
    "taxExemption": 100,
    "termsAndConditions": 250,
    "systemSpecifications": 200,
    "infrastructureDiagram": None,  # No specific word limit (usually visual representation).
    "hardwareSpecifications": 150,
    "proposedSolutionArchitecture": 200,
    "serverSSLSpecifications": 100,
    "serviceDeliveryPolicies": 150,
    "testingAndQualityAssurance": 150,
    "serviceWarrantyAndSupport": 150,
    "liability": 100,
    "benefitsAndOutcomes": 200,
    "riskAssessment": 150,
    "references": None,  # No specific word limit (list of references).
    "ethicalConsideration": 150,
    "conclusion": 100
}
